// This file is auto-generated by @better-auth/cli
// Run: npx @better-auth/cli generate --config ./convex/betterAuth/auth.ts --output ./convex/betterAuth/schema.ts
//
// PLACEHOLDER: This will be generated once `npx convex dev` runs and types are available.
// For now, export an empty schema to satisfy imports.

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    // Better Auth managed tables — auto-generated
    user: defineTable({
        name: v.string(),
        email: v.string(),
        emailVerified: v.boolean(),
        image: v.optional(v.string()),
        createdAt: v.number(),
        updatedAt: v.number(),
    }).index("email", ["email"]),

    session: defineTable({
        expiresAt: v.number(),
        token: v.string(),
        createdAt: v.number(),
        updatedAt: v.number(),
        ipAddress: v.optional(v.string()),
        userAgent: v.optional(v.string()),
        userId: v.string(),
    })
        .index("token", ["token"])
        .index("userId", ["userId"]),

    account: defineTable({
        accountId: v.string(),
        providerId: v.string(),
        userId: v.string(),
        accessToken: v.optional(v.string()),
        refreshToken: v.optional(v.string()),
        idToken: v.optional(v.string()),
        accessTokenExpiresAt: v.optional(v.number()),
        refreshTokenExpiresAt: v.optional(v.number()),
        scope: v.optional(v.string()),
        password: v.optional(v.string()),
        createdAt: v.number(),
        updatedAt: v.number(),
    })
        .index("userId", ["userId"])
        .index("accountId_providerId", ["accountId", "providerId"]),

    verification: defineTable({
        identifier: v.string(),
        value: v.string(),
        expiresAt: v.number(),
        createdAt: v.optional(v.number()),
        updatedAt: v.optional(v.number()),
    }).index("identifier", ["identifier"]),
});
